apiVersion: apps/v1
kind: Deployment
metadata:
  name: magic-deployment
  labels:
    app: magic
  namespace: mainnet
spec:
  replicas: 1
  selector:
    matchLabels:
      app: magic
  template:
    metadata:
      labels:
        app: magic
    spec:
      containers:
      - name: magic-prod
        image: registry.gitlab.com/ngrave/rana/app/be/magic_prod:main
        imagePullPolicy: Always
        ports:
        - containerPort: 3333
        env:
          - name: INFURA_API_KEY
            valueFrom:
              secretKeyRef:
                name: rick-env-secrets
                key: INFURA_API_KEY
          - name: MORTY_API_URL
            value: "http://morty.mainnet.svc.cluster.local"
          - name: SENTRY_DSN
            valueFrom:
              configMapKeyRef:
                name: magic-sentry-config
                key: sentry_dsn
          - name: SENTRY_TRACES_SAMPLE_RATE
            valueFrom:
              configMapKeyRef:
                name: magic-sentry-config
                key: sentry_traces_sample_rate
          - name: SENTRY_ENVIRONMENT
            valueFrom:
              configMapKeyRef:
                name: magic-sentry-config
                key: sentry_environment
          - name: RICK_DB_HOST
            value: "rick-db-service.mainnet.svc.cluster.local"
          - name: RICK_DB_PORT
            value: "5432"
          - name: MORALIS_API_KEY
            valueFrom:
              secretKeyRef:
                name: rick-env-secrets
                key: MORALIS_API_KEY
        envFrom:
        - configMapRef:
            name: proxyconfig
        volumeMounts:
        - name: cacert
          mountPath: /etc/ssl/certs/ca_cert.pem
          subPath: ca_cert.pem
        resources:
          requests:
            cpu: "100m"
            memory: "64Mi"
          # limits:
          #   cpu: "500m"
          #   memory: "1024Mi"
      imagePullSecrets:
        - name: gitlabregistry
      volumes:
      - name: cacert
        configMap:
          name: proxyca
          items:
            - key: ca_cert.pem
              path: ca_cert.pem