export enum EEnvironment {
  etherscanAPIKey = 'etherscan_api_key',
  princessAPIUrl = 'princess_api_url',
  moralisAPIKey = 'moralis_api_key',
  alchemyMainnetAPIKey = 'alchemy_mainnet_api_key',
  alchemyGoerliAPIKey = 'alchemy_goerli_api_key',
  liquidAPIKey = 'liquid_api_key',
  liquidTestAPIKey = 'liquid_test_api_key',
  liquidAPIUrl = 'liquid__api_url',
  liquidTestAPIUrl = 'liquid_test_api_url',
  mortyAPIUrl = 'morty_api_url',
  webhookMainnetId = 'webhook_mainnet_id',
  webhookGoerliId = 'webhook_goerli_id',
  alchemyAuthToken = 'alchemy_auth_token',
}
