apiVersion: apps/v1
kind: Deployment
metadata:
  name: princess-deployment
  labels:
    app: princess
spec:
  replicas: 1
  selector:
    matchLabels:
      app: princess
  template:
    metadata:
      labels:
        app: princess
    spec:
      containers:
      - name: princess-prod
        image: registry.gitlab.com/ngrave/rana/app/be/princess_prod:main
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        env:
          - name: RICK_API_URL
            value: "http://rick.default.svc.cluster.local"
          - name: MORTY_API_URL
            value: "http://morty.default.svc.cluster.local"
          - name: GANDALF_API_URL
            value: "http://gandalf.default.svc.cluster.local"
          - name: FIDELITY_CLIENT_ID
            valueFrom:
              secretKeyRef:
                name: princess-env-secrets
                key: FIDELITY_CLIENT_ID
          - name: FIDELITY_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: princess-env-secrets
                key: FIDELITY_CLIENT_SECRET
        resources:
          requests:
            cpu: "20m"
            memory: "64Mi"
          limits:
            cpu: "50m"
            memory: "256Mi"
      imagePullSecrets:
        - name: gitlabregistry