apiVersion: apps/v1
kind: Deployment
metadata:
  name: princess-deployment
  labels:
    app: princess
spec:
  replicas: 1
  selector:
    matchLabels:
      app: princess
  template:
    metadata:
      labels:
        app: princess
    spec:
      containers:
      - name: princess-prod
        image: registry.gitlab.com/ngrave/rana/app/be/princess_prod:main
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        env:
          - name: JWT_SECRET
            valueFrom:
              secretKeyRef:
                name: princess-env-secrets
                key: JWT_SECRET
          - name: JWT_REFRESH_TOKEN_SECRET
            valueFrom:
              secretKeyRef:
                name: princess-env-secrets
                key: JWT_M_SECRET
          - name: RICK_API_URL
            value: "http://rick.default.svc.cluster.local"
          - name: MORTY_API_URL
            value: "http://morty.default.svc.cluster.local"
          - name: GANDALF_API_URL
            value: "http://gandalf.default.svc.cluster.local"
          - name: FLUFFY_API_URL
            value: "http://fluffy.default.svc.cluster.local"
          - name: KAFO_API_URL
            value: "http://kafo.default.svc.cluster.local"
          - name: BRISTLE_API_URL
            value: "http://bristle.default.svc.cluster.local"
          - name: FIDELITY_CLIENT_ID
            valueFrom:
              secretKeyRef:
                name: princess-env-secrets
                key: FIDELITY_CLIENT_ID
          - name: FIDELITY_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: princess-env-secrets
                key: FIDELITY_CLIENT_SECRET
          - name: SENTRY_DSN
            valueFrom:
              configMapKeyRef:
                name: princess-sentry-config
                key: sentry_dsn
          - name: SENTRY_TRACES_SAMPLE_RATE
            valueFrom:
              configMapKeyRef:
                name: princess-sentry-config
                key: sentry_traces_sample_rate
          - name: SENTRY_ENVIRONMENT
            valueFrom:
              configMapKeyRef:
                name: princess-sentry-config
                key: sentry_environment
          - name: INFURA_API_KEY
            valueFrom:
              secretKeyRef:
                name: rick-env-secrets
                key: INFURA_API_KEY
        envFrom:
        - configMapRef:
            name: proxyconfig
        volumeMounts:
        - name: cacert
          mountPath: /etc/ssl/certs/ca_cert.pem
          subPath: ca_cert.pem
        resources:
          requests:
            cpu: "50m"
            memory: "64Mi"
          limits:
            cpu: "150m"
            memory: "512Mi"
      imagePullSecrets:
        - name: gitlabregistry
      volumes:
      - name: cacert
        configMap:
          name: proxyca
          items:
            - key: ca_cert.pem
              path: ca_cert.pem