image: node:18

stages:
  - lint
  - test
  - build
  - deploy

.distributed:
  interruptible: true
  only:
    - main
    - merge_requests
  cache:
    key:
      files:
        - yarn.lock
    paths:
      - .yarn/
  before_script:
    - yarn install --frozen-lockfile --cache .yarn --prefer-offline
    - NX_HEAD=$CI_COMMIT_SHA
    - NX_BASE=${CI_MERGE_REQUEST_DIFF_BASE_SHA:-$CI_COMMIT_BEFORE_SHA}
  artifacts:
    paths:
      - node_modules/.cache/nx

lint-all:
  stage: lint
  extends: .distributed
  script:
    - npx nx workspace-lint --base=$NX_BASE --head=$NX_HEAD

lint:commit:
  stage: lint
  script:
    - echo "${CI_COMMIT_MESSAGE}" | npx commitlint

lint:
  stage: lint
  extends: .distributed
  script:
    - npx nx affected --base=$NX_BASE --head=$NX_HEAD --target=lint --parallel=3

test:
  stage: test
  extends: .distributed
  services:
    - postgres:15.2-alpine
  variables:
    PG_HOST: postgres
    PG_PORT: 5432
    POSTGRES_DB: testdb
    POSTGRES_USER: pguser
    POSTGRES_PASSWORD: pgpassword
    GANDALF_DB_USERNAME: $POSTGRES_USER
    RICK_DB_USERNAME: $POSTGRES_USER
    FLUFFY_DB_USERNAME: $POSTGRES_USER
    GANDALF_DB_PASSWORD: $POSTGRES_PASSWORD
    RICK_DB_PASSWORD: $POSTGRES_PASSWORD
    FLUFFY_DB_PASSWORD: $POSTGRES_PASSWORD
    GANDALF_DB_HOST: $PG_HOST
    RICK_DB_HOST: $PG_HOST
    FLUFFY_DB_HOST: $PG_HOST
    GANDALF_DB_PORT: $PG_PORT
    RICK_DB_PORT: $PG_PORT
    FLUFFY_DB_PORT: $PG_PORT
  script:
    - npx nx affected --base=$NX_BASE --head=$NX_HEAD --target=test --parallel=3 --ci --code-coverage

build:
  stage: build
  extends: .distributed
  script:
    - npx nx affected --base=$NX_BASE --head=$NX_HEAD --target=build --parallel=3

.push_to_registry:
  image: docker:20.10.16
  stage: build
  services:
    - docker:20.10.16-dind
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $IMAGE_TAG . --target=$BUILD_TARGET
    - docker push $IMAGE_TAG
  variables:
    BUILD_TARGET: "${APP}_prod"
    IMAGE_TAG: "${CI_REGISTRY_IMAGE}/${BUILD_TARGET}:${CI_COMMIT_REF_SLUG}"
  rules:
    - if: '$CI_COMMIT_BRANCH != "main"'
      when: never
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: never
    - changes:
        - "apps/$APP/*"
      when: on_success

push princess to registry:
  extends: .push_to_registry
  variables:
    APP: princess

push anton to registry:
  extends: .push_to_registry
  variables:
    APP: anton

push fluffy to registry:
  extends: .push_to_registry
  variables:
    APP: fluffy

push gandalf to registry:
  extends: .push_to_registry
  variables:
    APP: gandalf

push kafo to registry:
  extends: .push_to_registry
  variables:
    APP: kafo

push morty to registry:
  extends: .push_to_registry
  variables:
    APP: morty

push rick to registry:
  extends: .push_to_registry
  variables:
    APP: rick

deploy to k8s cluster:
  stage: deploy
  when: on_success
  image:
    name: bitnami/kubectl:latest
  script:
    - kubectl config use-context ngrave/rana/app/be:gke-agent
    - kubectl set image deployment/anton-deployment registry.gitlab.com/ngrave/rana/app/be/anton_prod:$CI_COMMIT_REF_SLUG
    - kubectl set image deployment/fluffy-deployment registry.gitlab.com/ngrave/rana/app/be/fluffy_prod:$CI_COMMIT_REF_SLUG
    - kubectl set image deployment/gandalf-deployment registry.gitlab.com/ngrave/rana/app/be/gandalf_prod:$CI_COMMIT_REF_SLUG
    - kubectl set image deployment/kafo-deployment registry.gitlab.com/ngrave/rana/app/be/kafo_prod:$CI_COMMIT_REF_SLUG
    - kubectl set image deployment/morty-deployment registry.gitlab.com/ngrave/rana/app/be/morty_prod:$CI_COMMIT_REF_SLUG
    - kubectl set image deployment/princess-deployment registry.gitlab.com/ngrave/rana/app/be/princess_prod:$CI_COMMIT_REF_SLUG
    - kubectl set image deployment/rick-deployment registry.gitlab.com/ngrave/rana/app/be/rick_prod:$CI_COMMIT_REF_SLUG
  environment:
    name: testnet gke cluster
    url: http://34.120.165.191
  rules:
    - if: '$CI_COMMIT_BRANCH != "main"'
      when: never
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: never