apiVersion: apps/v1
kind: Deployment
metadata:
  name: fluffy-deployment
  labels:
    app: fluffy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fluffy
  template:
    metadata:
      labels:
        app: fluffy
    spec:
      containers:
      - name: fluffy-prod
        image: registry.gitlab.com/ngrave/rana/app/be/fluffy_prod:main
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        env:
          - name: FLUFFY_DB_HOST
            value: "fluffy-db-service.default.svc.cluster.local"
        resources:
          requests:
            cpu: "20m"
            memory: "64Mi"
          limits:
            cpu: "50m"
            memory: "256Mi"
      imagePullSecrets:
        - name: gitlabregistry