apiVersion: apps/v1
kind: Deployment
metadata:
  name: fluffy-deployment
  labels:
    app: fluffy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fluffy
  template:
    metadata:
      labels:
        app: fluffy
    spec:
      containers:
      - name: fluffy-prod
        image: registry.gitlab.com/ngrave/rana/app/be/fluffy_prod:main
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        env:
          - name: FLUFFY_DB_HOST
            value: "fluffy-db-service.default.svc.cluster.local"
          - name: SENTRY_DSN
            valueFrom:
              configMapKeyRef:
                name: fluffy-sentry-config
                key: sentry_dsn
          - name: SENTRY_TRACES_SAMPLE_RATE
            valueFrom:
              configMapKeyRef:
                name: fluffy-sentry-config
                key: sentry_traces_sample_rate
          - name: SENTRY_ENVIRONMENT
            valueFrom:
              configMapKeyRef:
                name: fluffy-sentry-config
                key: sentry_environment
        resources:
          requests:
            cpu: "20m"
            memory: "64Mi"
          limits:
            cpu: "50m"
            memory: "256Mi"
      imagePullSecrets:
        - name: gitlabregistry