export enum EEnvironment {
  fidelityClientId = 'fidelity_client_id',
  fidelityClientSecret = 'fidelity_client_secret',
  rickAPIUrl = 'rick_api_url',
  mortyAPIUrl = 'morty_api_url',
  gandalfAPIUrl = 'gandalf_api_url',
  fluffyAPIUrl = 'fluffy_api_url',
  kafoAPIUrl = 'kafo_api_url',
  magicAPIUrl = 'magic_api_url',
  version = 'version',
  bristleAPIUrl = 'bristle_api_url',
  jwtRefreshTokenSecret = 'jwt_refresh_token_secret',
  alchemyGoerliSigningKey = 'alchemy_goerli_signing_key',
  alchemyMainnetSigningKey = 'alchemy_mainnet_signing_key',
}
