apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: botkube-exec-role
  namespace: default
rules:
- apiGroups:
  - ""
  resources:
  - pods/exec
  verbs:
  - create
  - get
  - list
  - watch
  - update
  - delete
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  - deployments/scale
  verbs:
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: botkube-exec-binding
  namespace: default
subjects:
- kind: User
  name: botkube-internal-static-user
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: botkube-exec-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: botkube-exec-role
  namespace: mainnet
rules:
- apiGroups:
  - ""
  resources:
  - pods/exec
  verbs:
  - create
  - get
  - list
  - watch
  - update
  - delete
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  - deployments/scale
  verbs:
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: botkube-exec-binding
  namespace: mainnet
subjects:
- kind: User
  name: botkube-internal-static-user
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: botkube-exec-role
  apiGroup: rbac.authorization.k8s.io
