apiVersion: apps/v1
# Why statefulset here? Because https://cloud.google.com/kubernetes-engine/docs/concepts/persistent-volumes#deployments_vs_statefulsets
kind: StatefulSet
metadata:
  name: pgadmin4
  labels:
    app: pgadmin4
spec:
  replicas: 1
  serviceName: "pgadmin-service"
  selector:
    matchLabels:
      app: pgadmin4
  template:
    metadata:
      labels:
        app: pgadmin4
    spec:
      containers:
      - name: pgadmin4
        image: dpage/pgadmin4
        securityContext:
           runAsUser: 0
           runAsGroup: 0
        env:
          - name: PGADMIN_DEFAULT_EMAIL
            value: mohammed.irfan@ngrave.io
          - name: PGADMIN_DEFAULT_PASSWORD
            value: ffa65c44c95caa6ca038b315fa782b9b825e169bf13e5404314522450f915fab
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "100m"
            memory: "64Mi"
          limits:
            cpu: "2000m"
            memory: "512Mi"
        volumeMounts:
          - name: pgadmin-data
            mountPath: /var/lib/pgadmin
  volumeClaimTemplates:
  - metadata:
      name: pgadmin-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "standard"
      resources:
        requests:
          storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: pgadmin-service
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: pgadmin4
  ports:
  - port: 80
    targetPort: 80