apiVersion: v1
kind: Service
metadata:
  name: fluffy-db-service
  namespace: mainnet
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: fluffy-db
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432
