apiVersion: v1
kind: Service
metadata:
  name: gandalf-db-service
  namespace: mainnet
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: gandalf-db
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432
