apiVersion: apps/v1
kind: Deployment
metadata:
  name: morty-deployment
  labels:
    app: morty
  namespace: mainnet
spec:
  replicas: 1
  selector:
    matchLabels:
      app: morty
  template:
    metadata:
      labels:
        app: morty
    spec:
      containers:
      - name: morty-prod
        image: registry.gitlab.com/ngrave/rana/app/be/morty_prod:main
        imagePullPolicy: Always
        ports:
        - containerPort: 3333
        env:
          - name: PRINCESS_API_URL
            value: "http://princess.mainnet.svc.cluster.local"
          - name: COINMARKET_API_KEY
            valueFrom:
              secretKeyRef:
                name: morty-env-secrets
                key: COINMARKET_API_KEY
          - name: FIDELITY_CLIENT_ID
            valueFrom:
              secretKeyRef:
                name: princess-env-secrets
                key: FIDELITY_CLIENT_ID
          - name: FIDELITY_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: princess-env-secrets
                key: FIDELITY_CLIENT_SECRET
          - name: NODE_ENV
            value: "production"
        resources:
          requests:
            cpu: "20m"
            memory: "64Mi"
          limits:
            cpu: "50m"
            memory: "256Mi"
      imagePullSecrets:
        - name: gitlabregistry