apiVersion: apps/v1
kind: Deployment
metadata:
  name: princess-deployment
  labels:
    app: princess
  namespace: mainnet
spec:
  replicas: 1
  selector:
    matchLabels:
      app: princess
  template:
    metadata:
      labels:
        app: princess
    spec:
      containers:
      - name: princess-prod
        image: registry.gitlab.com/ngrave/rana/app/be/princess_prod:main
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        env:
          - name: JWT_SECRET
            valueFrom:
              secretKeyRef:
                name: princess-env-secrets
                key: JWT_SECRET
          - name: JWT_M_SECRET
            valueFrom:
              secretKeyRef:
                name: princess-env-secrets
                key: JWT_M_SECRET
          - name: RICK_API_URL
            value: "http://rick.mainnet.svc.cluster.local"
          - name: MORTY_API_URL
            value: "http://morty.mainnet.svc.cluster.local"
          - name: GANDALF_API_URL
            value: "http://gandalf.mainnet.svc.cluster.local"
          - name: FLUFFY_API_URL
            value: "http://fluffy.mainnet.svc.cluster.local"
          - name: KAFO_API_URL
            value: "http://kafo.mainnet.svc.cluster.local"
          - name: BRISTLE_API_URL
            value: "http://bristle.mainnet.svc.cluster.local"
          - name: FIDELITY_CLIENT_ID
            valueFrom:
              secretKeyRef:
                name: princess-env-secrets
                key: FIDELITY_CLIENT_ID
          - name: FIDELITY_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: princess-env-secrets
                key: FIDELITY_CLIENT_SECRET
          - name: SENTRY_DSN
            valueFrom:
              configMapKeyRef:
                name: princess-sentry-config
                key: sentry_dsn
          - name: SENTRY_TRACES_SAMPLE_RATE
            valueFrom:
              configMapKeyRef:
                name: princess-sentry-config
                key: sentry_traces_sample_rate
          - name: SENTRY_ENVIRONMENT
            valueFrom:
              configMapKeyRef:
                name: princess-sentry-config
                key: sentry_environment
        resources:
          requests:
            cpu: "20m"
            memory: "64Mi"
          limits:
            cpu: "50m"
            memory: "256Mi"
      imagePullSecrets:
        - name: gitlabregistry